const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const INCREMENT_BY_10 = "INCREMENT_BY_10";
const DECREMENT_BY_10 = "DECREMENT_BY_10";

export { INCREMENT, DECREMENT, INCREMENT_BY_10, DECREMENT_BY_10 }